# Generated by Django 5.0.9 on 2024-11-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('En espera', 'En espera'), ('Atendido', 'Atendido'), ('Atendido', 'Atendido')], max_length=50, verbose_name='Estado'),
        ),
    ]
